baseURL: https://andysalerno.com
theme: slick
title: andy salerno
languageCode: "en"
defaultContentLanguage: "en-us"

paginate: 7

permalinks:
  posts: /:year/:month/:filename/

taxonomies:
    category: categories
    tag: tags
    series: series

menu:
  main:
    - identifier: home
      name: Home
      title: Home 
      url: /
      weight: 1

    - identifier: posts
      name: Posts
      title: Writings
      url: /posts
      weight: 2

    - identifier: photography
      name: Photography
      title: Street photography
      url: /photography
      weight: 3

    - identifier: tags
      name: Tags
      title: Tags
      url: /tags
      weight: 4

    - identifier: about
      name: About
      title: About
      url: /about
      weight: 5


params:
  css: /custom.css
  mainSections: ["posts"]
  showMetaDates: true
  showMetaLinks: true
  showFullContent: false

  opengraph: false
  schema: false
  twitter_cards: false

markup:
  highlight:
    style: native